In [16]:
import pandas as pd
import numpy as np

In [31]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [32]:
df = pd.read_csv('C:\\Users\\ABC\\AppData\\Local\\Temp\\Rar$DIa8816.43631\\train.csv', usecols=['Age', 'Fare', 'Survived'])
df.dropna(inplace=True)
df.shape

(714, 3)

In [33]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [34]:
x = df.iloc[:,:-1]
y = df.iloc[:,0]

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
x_train.head(2)

     Survived   Age
328         1  31.0
73          0  26.0

In [36]:
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [37]:
accuracy_score(y_test, y_pred)

1.0

In [39]:
scores = cross_val_score( X, y, cv=5, scoring='accuracy')
print(scores)

NameError: name 'X' is not defined

In [42]:
kbin_age = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
kbin_Fare = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')

trf = ColumnTransformer([
    ('first', kbin_age, [0]),
    ('second', kbin_Fare, [1])
])

In [45]:
x_train_tef = trf.fit_transform(x_train)
x_test_tef = trf.transform(x_test)
trf.named_transformers_['first'].bin_edges_

array([array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])],
      dtype=object)

In [ ]:
output['']