In [26]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [27]:
df = pd.read_csv('C:\\Users\\ABC\\AppData\\Local\\Temp\\Rar$DIa16476.11412\\covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [28]:
# df['cough'].value_counts()
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)
X_train

    age  gender  fever   cough       city
91   38    Male    NaN    Mild      Delhi
20   12    Male   98.0  Strong  Bangalore
40   49  Female  102.0    Mild      Delhi
4    65  Female  101.0    Mild     Mumbai
57   49  Female   99.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
39   50  Female  103.0    Mild    Kolkata
67   65    Male   99.0    Mild  Bangalore
36   38  Female  101.0    Mild  Bangalore
30   15    Male  101.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi

[80 rows x 5 columns]

Mentos Zindagi

In [30]:
from sklearn.compose import ColumnTransformer

In [36]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender','city'])
],remainder='passthrough')

In [38]:
transformer.fit_transform(X_train).shape

(80, 7)

In [40]:
transformer.transform(X_test).shape

(20, 7)