In [1]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('c:\\Users\\ABC\\AppData\\Local\\Temp\\Rar$DRa6796.41463\\registered_companies.csv')
df.shape

C:\Users\ABC\AppData\Local\Temp\ipykernel_2496\77327579.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('c:\\Users\\ABC\\AppData\\Local\\Temp\\Rar$DRa6796.41463\\registered_companies.csv')

(1992170, 17)

In [ ]:
df.isnull()
df.isnull().sum()
df.dropna()

,CORPORATE_IDENTIFICATION_NUMBER,COMPANY_NAME,COMPANY_STATUS,COMPANY_CLASS,COMPANY_CATEGORY,COMPANY_SUB_CATEGORY,DATE_OF_REGISTRATION,REGISTERED_STATE,AUTHORIZED_CAP,PAIDUP_CAPITAL,INDUSTRIAL_CLASS,PRINCIPAL_BUSINESS_ACTIVITY_AS_PER_CIN,REGISTERED_OFFICE_ADDRESS,REGISTRAR_OF_COMPANIES,EMAIL_ADDR,LATEST_YEAR_ANNUAL_RETURN,LATEST_YEAR_FINANCIAL_STATEMENT
70,L01110GJ1991PLC015846,AMRAWORLD AGRICO LIMITED,ACTV,Public,Company limited by Shares,Non-govt company,21-06-1991,Gujarat,130000000.0,120300000.0,1110.0,Agriculture & allied,"24, LAXMI CHAMBERS, NAVJEEVAN PRESS ROAD,OPP. ...",ROC AHMEDABAD,amraworldagrico@gmail.com,31-03-2019,31-03-2019
71,L01110GJ1994PLC021066,TRANS TECHNO FOODS LIMITED,ULQD,Public,Company limited by Shares,Non-govt company,17-01-1994,Gujarat,220000000.0,211200000.0,1110.0,Agriculture & allied,B-2 SARITA DARSHAN OPP JAIHIND PRESSASHRAM ROAD,ROC AHMEDABAD,anish_shahcs@yahoo.com,31-03-2009,31-03-2006
72,L01110GJ1994PLC021368,GALAXY AGRICO EXPORTS LIMITED,ACTV,Public,Company limited by Shares,Non-govt company,23-02-1994,Gujarat,55000000.0,27316200.0,1110.0,Agriculture & allied,"236, Jai Kishan Industrial Estate,Behind Murli...",ROC AHMEDABAD,info@galaxyagrico.com,31-03-2019,31-03-2019
73,L01110GJ1996PLC029329,CHEMCRUX ENTERPRISES LIMITED,ACTV,Public,Company limited by Shares,Non-govt company,15-04-1996,Gujarat,60000000.0,49362800.0,1110.0,Agriculture & allied,"330, TRIVIA Complex,Natubhai Circle, Racecourse",ROC AHMEDABAD,girishshah@chemcrux.com,31-03-2019,31-03-2019
74,L01111GJ2011PLC068414,JIYA ECO-PRODUCTS LIMITED,ACTV,Public,Company limited by Shares,Non-govt company,27-12-2011,Gujarat,320000000.0,300732620.0,1111.0,Agriculture & allied,"SURVEY NO. 202/2/1, NAVAGAM (G),TALUKA VALLABH...",ROC AHMEDABAD,cfo@jiyaeco.com,31-03-2019,31-03-2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992152,U45500NL2016PTC013415,SUPREMACY AGRI-TECH INFRA PRIVATELIMITED,ACTV,Private,Company limited by Shares,Non-govt company,03-11-2016,Nagaland,30000000.0,30000000.0,45500.0,Construction,"26, NEAR OLD DAILY MARKETKALIBARI ROAD",ROC SHILLONG,supremacyagritech@gmail.com,31-03-2019,31-03-2019
1992153,U50100NL2013PTC008357,AYITO AUTO PRIVATE LIMITED,ACTV,Private,Company limited by Shares,Non-govt company,18-09-2013,Nagaland,30000000.0,20100000.0,50100.0,Wholesale and retail trade repair of motor veh...,"H. NO. 131, D BLOCK,DAROGAPATHAR VILLAGE",ROC SHILLONG,ikheto@hotmail.com,31-03-2018,31-03-2018
1992155,U50101NL2012PTC008325,OKUSA AUTOMOBILES PRIVATE LIMITED,ACTV,Private,Company limited by Shares,Non-govt company,28-08-2012,Nagaland,25000000.0,22500000.0,50101.0,Wholesale and retail trade repair of motor veh...,"H. NO. 143, WALFORDOPP. ARMY CANTONMENT",ROC SHILLONG,okusatoyota@yahoo.com,31-03-2019,31-03-2019
1992156,U50200NL2013PTC008356,YEPTHOMI MOTORS PRIVATE LIMITED,ACTV,Private,Company limited by Shares,Non-govt company,18-09-2013,Nagaland,30000000.0,21000000.0,50200.0,Wholesale and retail trade repair of motor veh...,MASJID ROADPURANA BAZAR,ROC SHILLONG,accountant@cityford.co.in,31-03-2017,31-03-2017
1992169,U74990NL2016PTC008397,NAGA MART PRIVATE LIMITED,ACTV,Private,Company limited by Shares,Non-govt company,29-02-2016,Nagaland,500000.0,100000.0,74990.0,Real estate renting and business activities,"T.K Angami Complex,",ROC SHILLONG,narolamongkum@gmail.com,31-03-2019,31-03-2019

In [ ]:
pd.get_dummies(df["COMPANY_CATEGORY"])

,Company Limited by Guarantee,Company limited by Shares,Unlimited Company
70,False,True,False
71,False,True,False
72,False,True,False
73,False,True,False
74,False,True,False
...,...,...,...
1992152,False,True,False
1992153,False,True,False
1992155,False,True,False
1992156,False,True,False
1992169,False,True,False

In [ ]:
df['column'].astype('category')

KeyError: 'column'