In [66]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [67]:
df = pd.read_csv('C:\\Users\\ABC\\AppData\\Local\\Temp\\Rar$DIa980.47132\\train.csv', sep=';',header=None, names=['text','emoting'])

In [68]:
df.head()

                                                text  emoting
0  ID,W,G,R,AB,H,1B,2B,3B,HR,BB,SO,SB,CS,HBP,BBHB...      NaN
1  1,60,162,558,5336,1280,891,247,31,111,460,840,...      NaN
2  3,86,161,677,5620,1492,1147,216,46,83,531,752,...      NaN
3  5,79,162,679,5550,1496,1088,262,63,83,543,879,...      NaN
4  7,96,162,780,5536,1458,990,265,40,163,561,933,...      NaN

In [69]:
df = df.dropna(subset=['emoting'])

In [70]:
df.isnull().sum()

text       0
emoting    0
dtype: int64

In [71]:
df['emoting'].unique()

array([], dtype=float64)

In [72]:
unique_emotions = df['emoting'].unique()
emotion_number = {}
i = 0
for emo in unique_emotions:
    emotion_number[emo] = i
    i += 1

    df['emoting'] = df['emotion'].map(emotion_number)

In [73]:
df

Empty DataFrame
Columns: [text, emoting]
Index: []

In [74]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [75]:
import string
def remove_punctuation(txt):
    return txt.translate(str.maketrans('', '', string.punctuation))

In [76]:
df['text'] = df['text'].apply(remove_punctuation)

In [77]:
def remove_numders(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new += i
            return new
        df['text'] = df['text'].apply(remove_numders)

In [78]:
import nltk

In [79]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [80]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

False

In [81]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [87]:
df.loc[1]['text']

KeyError: 1