In [13]:
import numpy as np
import pandas as pd
df = pd.read_csv('C:\\Users\\ABC\\AppData\\Local\\Temp\\Rar$DIa7384.29013\\customers.csv')
df.sample(5)

           id             name    segment       state             city
424  EB-13975       Erica Bern  Corporate  California        Fairfield
361  RD-19585         Rob Dowd   Consumer    Kentucky        Henderson
130  BP-11185     Ben Peterman  Corporate    Colorado           Arvada
310  PG-18820  Patrick Gardner   Consumer  California    San Francisco
2    SO-20335   Sean O'Donnell   Consumer     Florida  Fort Lauderdale

In [14]:
df = df.iloc[:,1:]
df.head()

              name    segment           state             city
0      Claire Gute   Consumer        Kentucky        Henderson
1  Darrin Van Huff  Corporate      California      Los Angeles
2   Sean O'Donnell   Consumer         Florida  Fort Lauderdale
3  Brosina Hoffman   Consumer      California      Los Angeles
4     Andrew Allen   Consumer  North Carolina          Concord

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,:2],df.iloc[:,1],test_size=0.2)
from sklearn.preprocessing import OrdinalEncoder

In [20]:
x_train

                name      segment
631       Brian Derr     Consumer
213   Darren Koutras     Consumer
707      Heather Jas  Home Office
442   Aaron Smayling    Corporate
277      Seth Vernon     Consumer
..               ...          ...
390  Penelope Sewall  Home Office
348      Greg Hansen     Consumer
98       Joseph Holt     Consumer
36   Julie Creighton    Corporate
632     Chris McAfee     Consumer

[634 rows x 2 columns]

In [24]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Low','Medium','High'],['Basic','Standard','Premium']])
# oe.fit(x_train)
x_train = oe.fit_transform(x_train)

ValueError: Found unknown categories ['Brad Thomas', 'Sibella Parks', 'Adam Bellavance', 'Dianna Arnett', 'Patrick Ryan', 'Sandra Glassco', 'Richard Eichhorn', 'Steven Roelle', 'Maureen Fritzler', 'Michael Grace', 'Yana Sorensen', 'Edward Nazzal', 'Helen Andreada', 'Deanra Eno', 'Michael Dominguez', 'Doug Jacobs', 'Frank Olsen', 'Rick Huthwaite', 'Astrea Jones', 'Carlos Soltero', 'Amy Hunt', 'Brenda Bowman', 'Brooke Gillingham', 'Irene Maddox', 'Harry Marie', 'Tanja Norvell', 'Nick Zandusky', 'Brian Moss', 'Edward Hooks', 'Kalyca Meade', 'Barry Gonzalez', 'Thea Hudgings', 'Ken Dana', 'Anthony Witt', 'Mick Hernandez', 'Guy Armstrong', 'Victoria Pisteka', 'Darren Budd', 'Carlos Meador', 'Dan Lawera', 'Grace Kelly', 'Emily Phan', 'Pierre Wener', 'Helen Abelman', 'Jim Epp', 'Jack Garza', 'Chad McGuire', 'Kelly Andreada', 'Dan Campbell', 'Giulietta Weimer', 'Frank Hawley', 'Laurel Workman', 'Frank Preis', 'Brendan Dodson', 'Karl Braun', 'Greg Maxwell', 'Zuschuss Donatelli', 'Joy Daniels', 'Odella Nelson', 'Craig Carreira', 'Robert Barroso', 'Brendan Murry', 'Ritsa Hightower', 'Joel Eaton', 'Steven Ward', 'Maureen Gnade', 'Don Weiss', 'Fred Wasserman', 'Matt Collister', 'Vivek Grady', 'Dean percer', 'Nicole Fjeld', 'Corey Roper', 'Joni Blumstein', 'Thomas Boland', 'Erica Smith', 'Keith Herrera', 'Bruce Stewart', 'Mike Kennedy', 'Philisse Overcash', 'Ed Jacobs', 'Anna Haberlin', 'Penelope Sewall', 'Nona Balk', 'Muhammed Lee', 'Duane Huffman', 'Chris McAfee', 'Ed Ludwig', 'Joseph Airdo', 'Justin MacKendrick', 'Maris LaWare', 'Beth Fritzler', 'Catherine Glotzbach', 'Jay Kimmel', 'Thais Sissman', 'Stephanie Ulpright', 'Carol Darley', 'Max Ludwig', 'David Philippe', 'Dionis Lloyd', 'Sam Craven', 'Kean Nguyen', 'Suzanne McNair', 'Kean Takahito', 'Ricardo Emerson', 'Jason Fortune-', 'Jennifer Patt', 'Jamie Frazer', 'Yoseph Carroll', 'Meg Tillman', 'Pauline Webber', 'Katherine Hughes', 'Anthony Garverick', 'Eleni McCrary', 'Mike Pelletier', 'David Smith', 'Karen Carlisle', 'Denise Leinenbach', 'Chuck Clark', 'Fred Harton', 'Chuck Magee', 'Jason Gross', 'Mick Crebagga', 'Ed Braxton', 'Sonia Cooley', 'Duane Benoit', 'Susan Pistek', 'Nat Gilpin', 'Harold Ryan', 'Seth Vernon', 'Marc Crier', 'Karen Ferguson', 'Corinna Mitchell', 'Justin Ritter', 'Natalie Webber', 'Nathan Cano', 'Sean Wendt', 'Sean Braxton', 'Harold Dahlen', 'Matt Connell', 'Tony Molinari', 'Sally Matthias', 'Art Foster', 'Carol Adams', 'Eric Hoffmann', 'Jason Klamczynski', 'Anemone Ratner', 'Alex Avila', 'Tamara Dahlen', 'Maribeth Schnelling', 'Carl Weiss', 'Ricardo Sperren', 'Adrian Shami', 'Ralph Arnett', 'Filia McAdams', 'Roy Collins', 'Bobby Odegard', 'Bill Overfelt', 'Herbert Flentye', 'Jim Kriz', 'Jocasta Rupert', 'Pamela Stobb', 'Tamara Chand', 'Rick Duston', 'Damala Kotsonis', 'Anthony Rawles', 'Eric Barreto', 'Todd Sumrall', 'Joy Bell-', 'Bradley Nguyen', 'Nick Crebassa', 'Maribeth Dona', 'Erica Hackney', 'Becky Martin', 'Tom Stivers', 'Theresa Coyne', 'Nora Paige', 'Tom Boeckenhauer', 'Barry Pond', 'Rick Wilson', 'Joni Wasserman', 'Bill Donatelli', "Rose O'Brian", 'Angele Hood', 'Grant Thornton', 'Erin Mull', 'Brad Eason', 'Evan Henry', 'Dave Brooks', 'Rob Beeghly', 'Dana Kaydos', 'Troy Blackwell', 'Greg Hansen', 'Sanjit Engle', "Russell D'Ascenzo", 'Alejandro Ballentine', 'Ted Butterfield', 'Don Miller', "Jas O'Carroll", 'Bobby Elias', 'Lynn Smith', 'Linda Southworth', 'Christina Anderson', 'Hunter Lopez', 'Ann Steele', 'Ken Brennan', 'Dorris liebe', 'Chad Sievert', 'Laurel Elliston', 'Julie Kriz', 'Mitch Gastineau', 'Dorothy Dickinson', 'Barry Weirich', 'Russell Applegate', 'Craig Yedwab', 'Toby Carlisle', 'Becky Pak', 'Jennifer Braxton', 'Shaun Weien', 'Aaron Hawkins', "Sean O'Donnell", 'Roland Fjeld', 'Toby Braunhardt', 'Michael Kennedy', 'Matt Hagelstein', 'Bryan Spruell', 'Katherine Murray', 'Peter Buhler', 'Rick Reed', 'Paul MacIntyre', 'Larry Blacks', 'Bobby Trafton', 'John Grady', 'Allen Armold', 'Tiffany House', 'Neil Knudson', 'Kean Thornton', 'Julie Creighton', 'Mathew Reese', 'Arthur Prichep', 'Janet Molinari', 'Paul Van Hugh', 'Don Jones', 'Jennifer Jackson', 'Cindy Stewart', 'Sung Shariari', 'Chuck Sachs', 'Dennis Bolton', 'Luke Foster', 'Carlos Daly', 'Alejandro Savely', 'Sally Hughsby', 'Frank Atkinson', 'Justin Ellison', 'Gene Hale', 'Randy Bradley', 'Keith Dawkins', 'Jonathan Howell', 'Susan Vittorini', 'Lisa Ryan', 'Michelle Tran', 'Dianna Wilson', 'Anthony Jacobs', 'Sonia Sunley', 'Greg Guthrie', 'Alice McCarthy', 'Thomas Thornton', 'Mark Hamilton', 'Victoria Wilson', 'Denny Joy', 'Anna Gayman', 'Doug Bickford', 'Andy Gerbode', 'Anthony Johnson', 'Bill Shonely', 'Karen Seio', 'Darrin Sayre', 'Brendan Sweed', 'James Lanier', 'Andrew Allen', 'Denise Monton', 'Julia West', 'Michelle Ellison', 'Dan Reichenbach', 'Tracy Blumstein', 'Magdelene Morse', "Patrick O'Brill", 'Gene McClure', 'Daniel Lacy', 'Dianna Vittorini', 'Maribeth Yedwab', 'Christopher Conant', 'Dave Hallsten', 'Paul Prost', 'Annie Thurman', 'Paul Knutson', 'Ross Baird', 'Jane Waco', 'Fred McMath', 'Christopher Schild', 'Barry Franz', 'Ralph Kennedy', 'Cynthia Arntzen', 'Sylvia Foulston', 'Edward Becker', 'Skye Norling', 'Theresa Swint', 'Mark Packer', 'Steve Carroll', 'Marina Lichtenstein', 'Alan Dominguez', 'Sung Chung', 'Sheri Gordon', 'Mick Brown', 'Sue Ann Reed', 'Katherine Ducich', 'Nathan Gelder', 'Greg Tran', 'Adam Shillingsburg', 'Anne Pryor', 'Patricia Hirasaki', 'Erin Ashbrook', 'Saphhira Shifley', 'Shirley Daniels', 'Nat Carroll', 'Christina VanderZanden', 'Aleksandra Gannaway', 'Steven Cartwright', 'Alyssa Crouse', 'Sam Zeldin', 'Todd Boyes', 'Mike Vittorini', 'John Lucas', 'Beth Thompson', 'Mitch Webber', 'Max Jones', 'Brosina Hoffman', 'Vivian Mathis', 'Philip Fox', 'Christy Brittain', 'Rob Dowd', 'Jim Karlsson', 'Charlotte Melton', 'Berenike Kampe', 'Eugene Moren', 'Helen Wasserman', 'Andy Yotov', 'Darren Powers', 'Michael Granlund', 'Joy Smith', 'Jim Mitchum', "Anthony O'Donnell", 'Rachel Payne', 'Robert Waldorf', 'Liz Preis', 'Frank Merwin', 'Ted Trevino', 'Joni Sundaresam', 'Stuart Van', 'Evan Bailliet', 'Jeremy Pistek', 'Sharelle Roach', 'Tracy Zic', 'Roy Phan', 'Michael Paige', 'Neil Ducich', 'Matt Collins', 'Shahid Hopkins', 'Pauline Johnson', 'Alex Grayson', 'Mike Caudle', 'Tom Ashbrook', 'Liz Carlisle', 'Allen Goldenen', 'Sean Miller', 'Clay Rozendal', 'Deborah Brumfield', "Meg O'Connel", 'Toby Ritter', 'Evan Minnotte', 'Nora Preis', 'Bradley Talbott', 'Ashley Jarboe', 'Thomas Seio', 'Bart Folk', 'Vicky Freymann', 'Erica Bern', 'Janet Martin', 'Marc Harrigan', 'Brian DeCherney', 'Art Ferguson', 'Denny Blanton', 'Christine Phan', 'Brian Dahlen', 'Matthew Clasen', 'Fred Chung', 'Tonja Turnell', 'Neola Schneider', 'Randy Ferguson', 'Ben Peterman', 'Clytie Kelty', 'Resi Polking', 'Phillip Breyer', 'Cynthia Delaney', 'Katrina Willman', 'Michelle Lonsdale', 'Stefanie Holloman', 'Kimberly Carter', 'Benjamin Patterson', 'Lindsay Williams', 'Darrin Martin', 'Victor Preis', 'Natalie DeCherney', 'Dean Braden', 'Lindsay Shagiari', 'Jill Fjeld', 'Troy Staebel', 'Jamie Kunitz', 'Alan Barnes', 'Eugene Barchas', 'Jennifer Ferguson', 'Michelle Moray', 'Sarah Brown', 'Shaun Chance', 'Giulietta Dortch', 'Susan Gilcrest', 'Liz Pelletier', 'Craig Molinari', 'Ann Chong', 'Monica Federle', 'Barbara Fisher', 'Kelly Williams', 'Peter Fuller', 'Pete Kriz', 'Sandra Flanagan', 'John Lee', 'Gary Hwang', 'Mike Gockenbach', 'Tom Prescott', 'Parhena Norris', 'Stewart Visinsky', 'Lena Hernandez', 'Jenna Caffey', 'Shirley Jackson', 'Corey Catlett', 'Phillina Ober', 'Nora Pelletier', 'Anne McFarland', 'Giulietta Baptist', 'Muhammed MacIntyre', 'Jill Stevenson', 'Anna Chung', 'Stewart Carmichael', 'Rob Lucas', 'Nicole Brennan', 'Rick Bensley', 'Lisa DeCherney', 'Arthur Wiediger', 'Amy Cox', 'Deirdre Greer', "Jack O'Briant", 'Eileen Kiefer', 'Lisa Hazard', 'Sarah Foster', 'Becky Castell', 'Candace McMahon', 'Henry MacAllister', 'Khloe Miller', 'Lena Creighton', 'Tim Brockman', 'Dorothy Wardle', 'Kelly Lampkin', 'Joe Kamberova', 'Michael Moore', 'Sarah Jordon', 'Sanjit Chand', 'Jim Sink', 'Jeremy Lonsdale', 'Denny Ordway', 'Logan Haushalter', 'James Galang', 'Larry Tron', 'Gary Hansen', 'Michael Chen', 'Trudy Schmidt', 'Tamara Manning', 'Bart Watters', 'Ivan Liston', 'Adrian Hane', 'Lindsay Castell', 'Eva Jacobs', 'Noel Staavos', 'Rob Haberlin', 'Alejandro Grove', 'Delfina Latchford', 'Larry Hughes', 'Chad Cunningham', 'Jonathan Doherty', 'Heather Jas', 'Lena Radford', 'Toby Swindell', 'Shirley Schmidt', 'Corey-Lock', 'Robert Dilbeck', 'Naresj Patel', 'Ryan Crowe', 'Cyma Kinney', 'Matthew Grinstein', 'Dennis Pardue', 'Cari Sayre', 'Nancy Lomonaco', 'Bryan Mills', 'Roland Murray', 'Julia Dunbar', 'Patrick Bzostek', 'Julia Barnett', 'Joe Elijah', 'Heather Kirkland', 'Stuart Calhoun', 'Bill Eplett', 'Henia Zydlo', 'Logan Currie', 'Gary Zandusky', 'Carol Triggs', 'Duane Noonan', 'Patrick Gardner', 'Noah Childs', 'MaryBeth Skach', 'Ross DeVincentis', 'Ann Blume', 'Bill Stewart', 'Allen Rosenblatt', 'Alyssa Tate', 'Jessica Myrick', 'Jennifer Halladay', 'Valerie Mitchum', 'George Zrebassa', 'Georgia Rosenberg', 'Charles McCrossin', 'Zuschuss Carroll', 'Chloris Kastensmidt', 'Maurice Satty', 'Raymond Buch', 'Michael Nguyen', 'Susan MacKendrick', 'Toby Gnade', 'Julie Prescott', 'Dave Kipp', 'Caroline Jumper', 'Liz MacKendrick', 'Elizabeth Moffitt', 'Bruce Geld', 'Michelle Huthwaite', 'Vivek Sundaresam', 'Dean Katz', 'Daniel Raglin', 'Sally Knutson', 'Alan Shonely', 'Chris Selesnick', 'Roger Demir', 'David Kendrick', 'Scott Williamson', 'Pete Takahito', 'Andrew Roberts', 'Liz Thompson', 'Shahid Shariari', 'David Flashing', 'Nick Radford', 'Quincy Jones', 'Cathy Armstrong', 'Andy Reiter', 'Bill Tyler', 'Liz Willingham', 'Bryan Davis', 'Christine Abelman', 'Eudokia Martin', 'Darrin Van Huff', 'Kristen Hastings', 'Erin Creighton', 'Joseph Holt', 'Ken Lonsdale', "Doug O'Connell", 'John Dryer', 'Aaron Bergman', 'Mary Zewe', 'Cindy Chapman', 'Ryan Akin', 'Ruben Ausman', 'Ben Ferrer', 'Pauline Chand', 'Vivek Gonzalez', 'Trudy Brown', 'Hunter Glantz', 'Sarah Bern', 'Brian Stugart', 'Paul Gonzalez', 'Mark Cousins', 'Ruben Dartt', 'Michael Stewart', 'Lycoris Saunders', 'Charles Sheldon', 'Neoma Murray', 'Nicole Hansen', 'Mitch Willingham', 'Emily Grady', 'Katharine Harms', 'Gary McGarr', 'Bart Pistole', 'Olvera Toch', 'Jill Matthias', 'Maxwell Schwartz', 'Aaron Smayling', 'Gary Mitchum', 'Katrina Edelman', 'Lela Donovan', 'Kelly Collister', 'Peter McVee', 'Cindy Schnelling', 'Kristina Nunn', 'Ralph Ritter', 'John Murray', 'Speros Goranitis', 'Tony Chapman', 'Sanjit Jacobs', 'Laurel Beltran', 'Chris Cortes', 'Darren Koutras', 'Brian Derr', 'Tracy Poddar', 'Greg Matthias', "Mary O'Rourke", 'Claire Gute', 'Valerie Dominguez', 'Maria Zettner'] in column 0 during fit