In [8]:
import numpy as np
import pandas as pd

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier

In [13]:
df = pd.read_csv('C:\\Users\\ABC\\AppData\\Local\\Temp\\Rar$DIa14148.38694\\train.csv')
df.head()

,ID,W,G,R,AB,H,1B,2B,3B,HR,...,HBP,BBHBP,SF,Outs,Outsinplay,RA,BA,OBA,SLG,OPS
0,1,60,162,558,5336,1280,891,247,31,111,...,0,460,0,4056,3216,740,0.239880,0.300207,0.360195,0.660402
1,3,86,161,677,5620,1492,1147,216,46,83,...,0,531,0,4128,3376,643,0.265480,0.328890,0.364591,0.693480
2,5,79,162,679,5550,1496,1088,262,63,83,...,0,543,0,4054,3175,710,0.269550,0.334646,0.384324,0.718971
3,7,96,162,780,5536,1458,990,265,40,163,...,0,561,0,4078,3145,682,0.263367,0.331146,0.414017,0.745164
4,9,96,162,688,5441,1354,905,247,21,181,...,55,597,35,4087,2703,548,0.248851,0.321258,0.401764,0.723022

let's plan

In [14]:
df.drop(columns=['Outsinplay','HBP','Outs'],inplace=True)

In [17]:
# step1: train test split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['BBHBP']),df['BBHBP'],test_size=0.2,random_state=42)
x_train.head()

,ID,W,G,R,AB,H,1B,2B,3B,HR,BB,SO,SB,CS,SF,RA,BA,OBA,SLG,OPS
431,863,65,162,597,5403,1294,911,246,31,106,489,981,112,49,0,734,0.239497,0.302614,0.355358,0.657972
208,417,98,162,769,5589,1484,1042,223,28,191,588,896,114,62,0,582,0.265522,0.335438,0.417964,0.753402
184,369,94,162,634,5486,1345,876,273,35,161,469,1330,94,42,29,577,0.245170,0.313241,0.395735,0.708976
177,355,86,161,712,5451,1432,959,284,22,167,449,1051,114,52,41,743,0.262704,0.322543,0.414786,0.737329
192,385,78,162,813,5581,1457,927,305,38,187,522,1142,71,18,57,828,0.261064,0.327056,0.429851,0.756907

In [18]:
y_train.sample(5)

517    653
406    475
210    633
28     478
327    540
Name: BBHBP, dtype: int64