In [23]:
import numpy as np
import pandas as pd

In [24]:
date = pd.read_csv('c:\\Users\ABC\AppData\Local\Temp\Rar$DRa11048.31982\message.csv')
time = pd.read_csv('c:\\Users\ABC\AppData\Local\Temp\Rar$DRa15232.4674\orders.csv')

In [25]:
date.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [26]:
time.head()

       id  order_date ship_mode customer_id    sales
0  100006  2014-09-07  Standard    DK-13375  377.970
1  100090  2014-07-08  Standard    EB-13705  699.192
2  100293  2014-03-14  Standard    NF-18475   91.056
3  100328  2014-01-28  Standard    JC-15340    3.928
4  100363  2014-04-08  Standard    JM-15655   21.376

In [27]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5009 entries, 0 to 5008
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           5009 non-null   int64
 1   order_date   5009 non-null   object
 2   ship_mode    5009 non-null   object
 3   customer_id  5009 non-null   object
 4   sales        5009 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 195.8+ KB

Working with date

In [33]:
# convert the date column to datetime format
date['v1'] = pd.to_datetime(date['v1'])
date.info()

C:\Users\ABC\AppData\Local\Temp\ipykernel_2212\3064763295.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date['v1'] = pd.to_datetime(date['v1'])

DateParseError: Unknown datetime string format, unable to parse: ham, at position 0

extract year

In [34]:
date['date_year'] = date['date'].dt.year

KeyError: 'date'